# website settings
website:
  title: "Pascal Bärtschi"                                
  description: "Pascal doing computational biology"   
  image: img/my_face.jpg
  
  favicon: img/favicon.ico
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd
      # - text: "Photography"
      #   href: photography/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      # - icon: folder-symlink
      #   href: tbd
      # - icon: twitter
      #   href: tbd
      - icon: github
        href: https://github.com/pascalbartschi
      - icon: linkedin
        href: https://www.linkedin.com/in/pascal-baertschi/
      - icon: envelope
        aria-label: email
        href: "mailto:bartschi.compbio@gmail.com"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2023 Pascal Bärtschi CC BY-SA 4.0</span>
    center: |
      <span class="faux-block"><a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">View the tutorial for this template!</a></span>
    right: |
      <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>
      <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme:
      dark: 
        - darkly
        - html/styles.scss
      light: 
        - flatly
        - html/styles.scss
      
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true